# Generated by Django 3.1.7 on 2021-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210306_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productonstorage',
            options={'verbose_name': 'Наличие товаров', 'verbose_name_plural': 'Наличие товаров на складе'},
        ),
        migrations.RemoveField(
            model_name='productonstorage',
            name='available',
        ),
        migrations.RemoveField(
            model_name='productonstorage',
            name='storage',
        ),
        migrations.AddField(
            model_name='productonstorage',
            name='storage',
            field=models.ManyToManyField(blank=True, to='main.Storage', verbose_name='Склады'),
        ),
    ]
