# Generated by Django 3.1.7 on 2021-03-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210306_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldproduct',
            options={'ordering': ('product',), 'verbose_name': 'Проданный товар', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.RenameField(
            model_name='soldproduct',
            old_name='name',
            new_name='product',
        ),
    ]
