# Generated by Django 3.1.7 on 2021-03-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210306_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shop'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.storage'),
        ),
    ]
